### ISSUE TITLE
Simulation speed surging & slowing as population rises.

### ISSUE THREAD

**Issue by Devieth** [CitiesSkylinesMods/TMPE#1009]
### Describe the problem

Simulation speed surges and slows as city population increases faster than expected with TM:PE enabled.

### Steps to reproduce

1.  Have a city with 25-35k in pop or greater (Inconsistent, have had it happen at 12k population before.)
2.  Enable TM:PE
3.  Watch traffic and time simulation surge and slow.

_Note: Over 100/150k population this behavior stops, but instead everything can start simulating slower than the slowest simulation speed would otherwise._

_This is possibly unrelated: When loading a save with 300k+ pop, after moving the camera simulation speed starts moving, incredibly slow (1 simulation step per second, as if I was getting 1FPS even though I'm getting 40.)_

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/5232582/output_log.txt)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?edit=true&id=2230475184

### Screenshots?

Video(TM:PE Disabled vs Enabled): https://streamable.com/dviq6h

### Notes or questions?
Related to this? _( https://github.com/CitiesSkylinesMods/TMPE/issues/814 )_

My framerate does not seem to be affected.  Also I don't remember this being as big of an issue for older versions of TM:PE, primarily noticed it when upgrading to v11+ due to the game update.

**Comment by Devieth** [comment]
Resolved or not as noticeable, cause appeared to be a broken Windows 10 install.

**Comment by krzychu124** [comment]
Interesting finding🤔 Let us know if issue persist _(we are working on performance improvements)_ 😉
