### ISSUE TITLE
Industries warehouses & facilities seems to not being able to spawn new vehicles

### ISSUE THREAD

**Issue by klyte45** [CitiesSkylinesMods/TMPE#1097]
> **Temporary Workaround** Use the [current dev version](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=master)

### Describe the problem

While playing today I noted that some buildings from Industries DLC wasn't being able to spawn vehicles to empty their stocks. I noted the bar showing the current fill rate have flashed like it will spawn a truck, but in next frame it got back to full state.

### Steps to reproduce

1.  Have a full Industries Warehouse
2. Set it to get empty
3. The trucks won't spawn

### Log files

I looked the logs and there's nothing that could help: no exceptions or logs at all from TMPE out of the usual. 
I know that is the TMPE (or an incompatible mod) that's cause the issue because right after disabling it and loading the city, the trucks finally started emptying the warehouse, as well selling products from other Industries buildings (in my case, it's a Farm area).

If need some kind of special test in my savegame (like a specific logging setting), just let me know. I have the savegame here stored.

### Savegame?
Too much modded to share, I believe. But, I can pass it if you want.

### Screenshots?

Nothing that could help, I guess.

**Comment by krzychu124** [comment]
Thanks for reporting the issue.

**Are yours warehouses are outside 25 tile area?** Latest (unreleased yet) build add support for pathfinding outside 25 tiles are making it fully compatible with 81Tiles mod.
Probably because that change I can't reproduce that issue using the latest `master` build or maybe I'm using wrong warehouse building? AFAIK there is only one vanilla AI for warehouses so probably that's not the case here😕
Test build is [available here](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=master) 

https://user-images.githubusercontent.com/19638970/116834500-b690a200-abbe-11eb-91b0-dab201f315ab.mp4

**Comment by klyte45** [comment]
Yep, it is outside of 25 tiles area.
I will check the master version and I tell you the results later.

**Comment by klyte45** [comment]
![image](https://user-images.githubusercontent.com/11671356/116835216-ee382380-ab97-11eb-9b5a-0e0cab2dc545.png)
Well, it worked.
I'll use this version while it don't go to Workshop. Thanks for attention!

**Comment by kianzarrin** [comment]
> Well, it worked.
I'll use this version while it don't go to Workshop.

@krzychu124 can we close this since it works in Test version (or is that what stable label meant to do)?

**Comment by krzychu124** [comment]
Yeah, we can close it, `Stable` label meant that the issue is visible on the Stable and only that one (problem was automatically fixed with Harmony migration)

**Comment by KrDimitrov** [comment]
Seems like this is happening again? My warehouses and some oil factories cant spawn their trucks, it goes to 1 and then 0. 
Even if i disable all features in the maintenance option tab, it still doesnt work. If i remove the mod from the mods folder then it works properly. I tried moving the structures around and changing the roads as well but nothing worked.
