### ISSUE TITLE
Timed traffic doesn't skip to next step even after max time

### ISSUE THREAD

**Issue by HawaiianPizza** [CitiesSkylinesMods/TMPE#893]
### Describe the problem

I set up timed traffic for one of my intersections with a minimum time of 5 seconds and a max time of 10 seconds. When it's supposed to move on to the next step by the 10-second mark, the timer resets and it stays in the same step.

### Steps to reproduce

1. Set up timed traffic on an intersection with multiple steps
2. Set a minimum and max time
3. Start timed traffic

### Log files

TPME log: https://ufile.io/at0mxgo4

### Video

https://streamable.com/kvzpz2

If you look at the Timed Traffic Lights Manager, you'll see that it resets the moment the max time runs out. 

---

Version 11.3.2, Build 11.3.2.32644 STABLE for game version 1.13.0-f8

**Comment by Xyrhenix** [comment]
Could you confirm that you didn't tick the box that disables step changes? I expect you haven't ticked it, but I'd like to be sure first.

**Comment by krzychu124** [comment]
Above error was already patched, but version **(v.11.5.0)** was not released yet.

**Comment by aubergine10** [comment]
The last two PRs for v11.5.0 are approved I think so we are close to release

**Comment by aubergine10** [comment]
Tagging #861 , #880

**Comment by aubergine10** [comment]
Fixed in v11.5.0 LABS

**Comment by HawaiianPizza** [comment]
> 
> 
> Fixed in v11.5.0 LABS

Just gave it a try again in LABS and it still doesn't work. Do I need to delete my timed traffic settings for it to work?

**Comment by aubergine10** [comment]
Please share updated log files (output_log.txt and TMPE.log)

**Comment by krzychu124** [comment]
Closing due to inactivity. Reopen or create new issue if problem still exist
